### ISSUE TITLE
Add lazy loading modules

### ISSUE THREAD

**Issue by farinalvaro** [rsksmart/rif-marketplace-ui#214]
Should be tackled after #213 
With this approach we would load modules only when needed.
https://es.reactjs.org/docs/code-splitting.html#reactlazy

**Comment by julianmrodri** [comment]
Providers are instantiated at the start of the application. First we need to split the app into modules.

**Comment by jurajpiar** [comment]
Closing, because there was a misunderstanding in the problem description. The Issue https://github.com/rsksmart/rif-marketplace-ui/issues/213 fully solves the problem. React's Lazy loading is not necessary to resolve it. Although it could be done to optimise the initial resource-drain of the project, it's really just an improvement (P-4).
